# v0.4.1
FROM apache/airflow:2.8.1-python3.9

# install your pip packages
RUN pip install --no-cache-dir \
    aind-slurm-rest==0.2.1 \
    aind-slurm-rest-v2==0.0.1 \
    pydantic==2.11.3 \
    pydantic-settings==2.9.1 \
    python-logging-loki==0.3.1
