from allenneuraldynamics/cuda-miniconda-jupyterlab:latest
LABEL maintainer "David Feng <david.feng@alleninstitute.org>"

RUN pip install -U --no-cache-dir tensorflow jax[cuda12_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html lightning lightning-bolts torchtyping torchvision

