from allenneuraldynamics/cuda-miniconda-jupyterlab:latest
LABEL maintainer "David Feng <david.feng@alleninstitute.org>"

RUN pip install -U --no-cache-dir lightning nvidia-dali-cuda120 tensorboard lightning-bolts torchtyping torchvision
