name: Publish iamra-signing-helper
on:
  push:
    branches:
      - feat-iamra-image
    # paths:
    #   - iamra-signing-helper/**
  workflow_dispatch:

jobs:
  get-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set-docker-tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v5
      - name: Compute new docker image tag
        id: set-docker-tag
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF_NAME})" >> "$GITHUB_ENV"
          echo "docker_tag=$(echo ${GITHUB_REF_NAME})-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
  publish:
    needs: get-docker-tag
    uses: AllenNeuralDynamics/.github/.github/workflows/release-publish-docker-image.yml@main
    with:
      working-directory: iamra-signing-helper
      docker-tag: ${{ needs.get-docker-tag.outputs.docker_tag }}
      image-name: iamra-signing-helper
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
