name: Publish r2u-rstudio
on:
  push:
    branches:
      - main
    paths:
      - r2u-rstudio/**
      - .github/workflows/publish_r2u_rstudio.yml
  workflow_dispatch:


env:
  IMAGE_NAME: r2u-rstudio
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compute new docker image tag
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF_NAME})" >> "$GITHUB_ENV"
          echo "docker_tag=$(echo ${GITHUB_REF_NAME})-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./${{ env.IMAGE_NAME }}
          push: true
          tags: |
            ghcr.io/allenneuraldynamics/${{ env.IMAGE_NAME }}:${{ env.docker_tag }}
            ghcr.io/allenneuraldynamics/${{ env.IMAGE_NAME }}:latest
