name: Tag and publish
on:
  push:
    branches:
      - main
    paths:
      - hortacloud-deployment/**
jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.output_version.outputs.new_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default_branch }}
        fetch-depth: 0
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Get version file name set variables
      run: |
        docker_file="./hortacloud-deployment/Dockerfile"
        first_line=$(head -n 1 $docker_file)
        old_version=${first_line:3}
        most_recent_commit=$(git log --oneline | head -1)
        echo "VERSION_FILE=$docker_file" >> "$GITHUB_ENV"
        echo "VERSION=${{ steps.tag_version.outputs.new_version }}" >> "$GITHUB_ENV"
    - name: Update version file with new version
      run: |
        grep "__version__" "$VERSION_FILE"
        sed -i --debug --expression="s|__version__.*|__version__ = \"${{ env.VERSION }}\"|" "$VERSION_FILE"
    - name: Set output
      id: output_version
      run: echo "new_version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
    - name: Commit and Push version bump
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "ci: version bump [skip actions]"
        add: ${{ env.VERSION_FILE }}
  publish:
    runs-on: ubuntu-latest
    needs: update_version
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./horta-deployment
          push: true
          tags: |
            ghcr.io/allenneuraldynamics/hortacloud-deployment:${{ needs.tag.outputs.new_version }}
            ghcr.io/allenneuraldynamics/hortacloud-deployment:latest
