name: Tag and publish
on:
  push:
    branches:
      - main
    paths:
      - hortacloud-deployment/**
jobs:
  tag:
    uses: AllenNeuralDynamics/aind-github-actions/.github/workflows/tag.yml@main
    secrets:
      SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./horta-deployment
          push: true
          tags: |
            ghcr.io/allenneuraldynamics/hortacloud-deployment:${{ needs.tag.outputs.new_version }}
            ghcr.io/allenneuraldynamics/hortacloud-deployment:latest
